# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  hugoUrl: https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz
  hugoTar: /tmp/hugo.tgz
steps:
- script: |
    wget -q -O $(hugoTar) $(hugoUrl)
    tar xzvf $(hugoTar)
    sudo rsync -av hugo /usr/local/bin/
  displayName: 'Install Hugo'
- script: |
    hugo
  displayName: 'Build Hugo Blog'
- script: |
    git config --global user.email "devops@kaikeru.com"
    git config --global user.name "Azure Build"
    git clone https://$(github.username):$(github.token)@github.com/kaikeru/kaikeru.github.io.git /tmp/blog
    rm -rf /tmp/blog/*
    rsync -av public/* /tmp/blog/
    cd /tmp/blog
    git add .
    git commit -m 'Autocommit from $(Build.DefinitionName) $(Build.BuildNumber)'
    git push origin
  displayName: 'Commit to kaikeru.github.io'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))


