# Description : The config for Hugo using the minmal theme.
# Author      : Kyle Wagner

baseURL = "https://www.kaikeru.com/"
languageCode = "en-us"
title = "kaikeru"
theme = "kaikeru"
copyright = "©️2020 - Kyle Wagner"
enableRobotsTXT = true
googleAnalytics = "UA-81904592-1"

[author]
  name = "Kyle Wagner"

[params]
  author = "Kyle Wagner"
  description = "Blog"
  font = "Open Sans" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "atom-one-dark"
  highlightLanguages = ["java", "python", "yaml", "bash", "dockerfile"]

# [[menu.main]]
#   url = "/"
#   name = "Home"
#   weight = 1

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.social]]
  url = "https://github.com/kaikeru/"
  name = "Github"
  weight = 1

[[menu.social]]
    url = "https://twitter.com/aKaikeru/"
    name = "Twitter"
    weight = 2

[[menu.social]]
    url = "https://www.linkedin.com/in/kaikeru/"
    name = "Linkedin"
    weight = 3

