baseURL = "https://kaikeru.github.io"
languageCode = "en-us"
title = "Kaikeru"
theme = "minimal"

[author]
  homepage = "https://github.com/kaikeru"
  name = "Kyle Wagner"

[params]
  author = "Calin Tataru"
  description = "Kyle Wagner - Thoughts on happiness"
  githubUsername = "kaikeru"
  accent = "#333"
  showBorder = true
  backgroundColor = "white"
  font = "Raleway" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "solarized-dark"
  highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/post/"
  name = "Posts"
  weight = 2

[[menu.main]]
  url = "http://nihongo.kaikeru.com"
  name = "Japanese Tools"
  weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
  url = "https://github.com/kaikeru/"
  name = "github"
  weight = 1

[[menu.icon]]
    url = "https://twitter.com/aKyleWagner/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/kaikeru/"
    name = "linkedin"
    weight = 3